data:
  clip_duration: 4
  eval:
  - augmentation: none
    category: Deepfake
    compressions:
    - c23
    contrast: false
    detection_level: video
    name: FFPP
    pack: false
    pair: false
    root_dir: ./datasets/ffpp/
    scale: 1.0
    types:
    - REAL
    - DF
    - FS
    - F2F
    - NT
  - category: Deepfake
    name: DFDC
    pack: false
    root_dir: ./datasets/dfdc/
    scale: 0.1
  - category: Deepfake
    name: CDF
    pack: false
    root_dir: ./datasets/cdf/
    scale: 1.0
  num_frames: 20
  train:
  - augmentation: normal+frame
    category: Deepfake
    compressions:
    - c23
    contrast: true
    detection_level: video
    name: FFPP
    pack: false
    pair: false
    root_dir: ./datasets/ffpp/
    scale: 1.0
    types:
    - REAL
    - DF
    - FS
    - F2F
    - NT
evaluator:
  batch_size: 24
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  - name: deepfake/cdf
    types:
    - accuracy
    - roc_auc
  - name: deepfake/dfdc
    types:
    - accuracy
    - roc_auc
  name: Evaluator
  num_workers: 8
model:
  adapter:
    frozen: false
    struct:
      type: 768-x-768-nln
      x: 256
    type: normal
  architecture: ViT-B/16
  decode_mode: 
    type: index
    indices: [6,7,8,9,10,11]
  op_mode:
    attn_mode: "patch"
    attn_driver: ["smax"]
  dropout: 0.5
  losses:
  - auc_roc
  name: Detector
  out_dim:
  - 2
  weight_decay: 0.01
system:
  deterministic_training: true
  evaluation_interval: 300
  mixed_precision: 'no'
  seed: 0
  training_eval_interval: 10
tracking:
  compare_fn: max
  default_project_prefix: version
  directory: logs/deepfake
  enabled: true
  main_metric: deepfake/ffpp/roc_auc
  project_name: deepfake
  tool: wandb
trainer:
  batch_size: 12
  learning_rate: 0.003
  max_steps: 3000
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  mode:
    type: normal
  name: Trainer
  num_workers: 8
