tracking:
  enabled: true
  project_name: comp-inv
  directory: logs/comp-inv

model:
  name: CompInvEncoder

data:
  num_frames: 50
  train:
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "DF"
        - "FS"
        - "F2F"
      pair: 1
  eval:
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "NT"
      pair: 1

trainer:
  name: CompInvTrainer
  batch_size: 4
  learning_rate: 0.0003
  max_steps: 3000
  num_workers: 8


evaluator:
  name: CompInvEvaluator
  batch_size: 6
  num_workers: 8

system:
  deterministic_training: true
  training_eval_interval: 10
  evaluation_interval: 100

