tracking:
  enabled: true
  project_name: comp-inv
  directory: logs/comp-inv

model:
  name: CompInvEncoder
  mode: 1
  adapter:
    struct:
      type: "768-x-768"
      x: 256

data:
  num_frames: 50
  train:
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "DF"
        - "FS"
        - "F2F"
        - "NT"
      pair: 1

trainer:
  name: CompInvTrainer
  batch_size: 5
  learning_rate: 0.01
  max_steps: 3000
  num_workers: 8


evaluator:
  name: CompInvEvaluator
  batch_size: 6
  num_workers: 8

system:
  deterministic_training: true
  training_eval_interval: 10
  evaluation_interval: 100

