tracking:
  enabled: true
  project_name: F2F
  directory: logs/cross-manipulation-c23

data:
  train:
    compressions:
    - c23
    types:
    - REAL
    - DF
    - FS
    - NT
  eval:
    - name: validation
      compressions:
      - c23
      types:
      - REAL
      - F2F

system:
  deterministic_training: true

model:
  decode_stride: 2

