tracking:
  enabled: true
  project_name: NT
  directory: logs/cross-manipulation-c23

data:
  train:
    compressions:
    - c23
    types:
    - REAL
    - DF
    - F2F
    - FS
  eval:
    - name: validation
      compressions:
      - c23
      types:
      - REAL
      - NT

system:
  deterministic_training: true

model:
  decode_stride: 2

