data:
  clip_duration: 2
  eval:
  - compressions:
    - c23
    category: Deepfake
    detection_level: video
    name: FFPP
    pack: 0
    pair: 0
    root_dir: ./datasets/ffpp/
    scale: 1.0
    types:
    - REAL
    - NT

  - category: Deepfake
    name: DFDC
    scale: 0.1
    
  - category: Deepfake
    name: CDF
    scale: 0.6

  num_frames: 10
  train:
  - compressions:
    - c23
    category: Deepfake
    detection_level: video
    name: FFPP
    pack: 0
    pair: 0
    contrast: 0
    root_dir: ./datasets/ffpp/
    scale: 1.0
    types:
    - REAL
    - DF
    - FS
    - F2F


evaluator:
  batch_size: 48
  metrics:
  - name: deepfake/ffpp
    types:
      - accuracy
      - roc_auc

  - name: deepfake/cdf
    types:
      - accuracy
      - roc_auc

  - name: deepfake/dfdc
    types:
      - accuracy
      - roc_auc

  name: Evaluator
  num_workers: 8

model:
  adapter:
    frozen: 0
    path: /home/od/Desktop/repos/dfd-clip/logs/comp-inv/comp-inv/mode1+256+resi+1e-2/last_weights.pt
    struct:
      type: 768-x-768
      x: 256
    type: pretrain
  architecture: ViT-B/16
  decode_indices: []
  decode_mode: stride
  decode_stride: 2
  dropout: 0.0
  weight_decay: 0.3
  losses:
  - name: auc_roc
    args:
      weight: 
        - 2.0
        - 1.0
  name: Detector
  out_dim:
  - 2

system:
  deterministic_training: true
  evaluation_interval: 100
  mixed_precision: 'no'
  seed: 0
  training_eval_interval: 10

tracking:
  compare_fn: max
  default_project_prefix: version
  directory: logs/deepfake
  enabled: true
  main_metric: deepfake/ffpp/roc_auc
  project_name: deepfake
  tool: wandb

trainer:
  batch_size: 48
  ema_ratio: 0.999
  learning_rate: 0.00005
  max_steps: 3000
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  mode: normal
  name: Trainer
  num_workers: 8
  teach_at: 50
