tracking:
  enabled: true
  project_name: deepfake
  directory: logs/deepfake

model:
  name: Detector
  out_dim: 
    - 2
  losses:
    - auc_roc
  adapter:
    type: pretrain
    frozen: 0
    path: /home/od/Desktop/repos/dfd-clip/logs/comp-inv/comp-inv/0504T0529/last_weights.pt

data:
  train:
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "DF"
        - "FS"
        - "F2F"
  eval:
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "NT"

trainer:
  name: Trainer
  batch_size: 10
  learning_rate: 0.0005
  max_steps: 3000
  num_workers: 8
  metrics:
    - name: Deepfake
      types:
        - accuracy
        - roc_auc


evaluator:
  name: Evaluator
  batch_size: 10
  num_workers: 8
  metrics:
    - name: Deepfake
      types:
        - accuracy
        - roc_auc

system:
  deterministic_training: true
  training_eval_interval: 10
  evaluation_interval: 100

