tracking:
  enabled: true
  project_name: deepfake
  directory: logs/deepfake

model:
  name: Detector
  out_dim: 
    - 2
  losses:
    - auc_roc
  adapter:
    type: pretrain
    frozen: 0
    path: /home/od/Desktop/repos/dfd-clip/logs/comp-inv/comp-inv/mode1+256+resi+1e-2/last_weights.pt
    struct:
      type: "768-x-768"
      x: 256
data:
  clip_duration: 5
  num_frames: 25
  train:
    - category: Deepfake
      name: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "DF"
        - "FS"
        - "F2F"
  eval:
    - category: Deepfake
      name: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "NT"

    - category: Deepfake
      name: DFDC
      scale: 0.1
      
    - category: Deepfake
      name: CDF
      scale: 0.1

trainer:
  name: Trainer
  batch_size: 8
  learning_rate: 0.0005
  max_steps: 3000
  num_workers: 8
  metrics:
    - name: deepfake/ffpp
      types:
        - accuracy
        - roc_auc

evaluator:
  name: Evaluator
  batch_size: 10
  num_workers: 8
  metrics:
    - name: deepfake/ffpp
      types:
        - accuracy
        - roc_auc
    - name: deepfake/cdf
      types:
        - accuracy
        - roc_auc
    - name: deepfake/dfdc
      types:
        - accuracy
        - roc_auc

system:
  deterministic_training: true
  training_eval_interval: 5
  evaluation_interval: 10

