data:
  clip_duration: 4
  eval:
  - augmentation: none
    category: Deepfake
    compressions:
    - c23
    contrast: 0
    contrast_pair: 0
    detection_level: video
    name: FFPP
    pack: 0
    pair: 0
    random_speed: 1
    root_dir: ./datasets/ffpp/
    scale: 1.0
    ssl_fake: 0
    types:
    - REAL
    - DF
    - FS
    - F2F
    - NT
    vid_ext: .avi
  - category: Deepfake
    name: DFDC
    pack: 0
    root_dir: ./datasets/dfdc/
    scale: 0.1
    vid_ext: .avi
  - category: Deepfake
    name: CDF
    pack: 0
    root_dir: ./datasets/cdf/
    scale: 1.0
    vid_ext: .avi
  num_frames: 20
  train:
  - augmentation: normal+frame
    category: Deepfake
    compressions:
    - c23
    contrast: 1
    contrast_pair: 0
    detection_level: video
    name: FFPP
    pack: 0
    pair: 0
    random_speed: 1
    root_dir: ./datasets/ffpp/
    scale: 1.0
    ssl_fake: 0
    types:
    - REAL
    - DF
    - FS
    - F2F
    - NT
    vid_ext: .avi
evaluator:
  batch_size: 24
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  - name: deepfake/cdf
    types:
    - accuracy
    - roc_auc
  - name: deepfake/dfdc
    types:
    - accuracy
    - roc_auc
  name: Evaluator
  num_workers: 8
model:
  adapter:
    type: none
  architecture: ViT-B/16
  concat_ref: 0
  decode_indices:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  decode_mode: index
  decode_stride: 2
  dropout: 0.5
  foundation: clip
  losses:
  - name: auc_roc
    args:
      label_smoothing: 0.1
  name: Detector
  op_mode:
    global_prediction: 1
    temporal_position: 1
  optimizer: sgd
  out_dim:
  - 2
  train_mode: {}
  weight_decay: 0.01
system:
  deterministic_training: true
  evaluation_interval: 300
  mixed_precision: 'no'
  seed: 0
  training_eval_interval: 10
tracking:
  compare_fn: max
  default_project_prefix: version
  directory: logs
  enabled: true
  main_metric: deepfake/ffpp/roc_auc
  project_name: test
  tool: wandb
trainer:
  batch_size: 12
  learning_rate: 0.003
  lr_scheduler: one_cycle
  max_steps: 3000
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  mode: normal
  mode_params: {}
  name: Trainer
  num_workers: 10