tracking:
  enabled: false
  project_name: deepfake
  directory: logs/multi_evidence

model:
  out_dim: 
    - 2
  losses:
    - auc_roc

data:
  train:
    - name: Deepfake
      dataset: FFPP
  eval:
    - name: Deepfake
      dataset: FFPP

trainer:
  batch_size: 10
  learning_rate: 0.0003
  max_steps: 10000
  num_workers: 8
  metrics:
    - name: Deepfake
      types:
        - accuracy
        - roc_auc


evaluator:
  batch_size: 8
  num_workers: 8
  metrics:
    - name: Deepfake
      types:
        - accuracy
        - roc_auc

system:
  deterministic_training: true
  training_eval_interval: 10
  evaluation_interval: 100

