data:
  clip_duration: 4
  eval:
  - augmentation: none
    category: Deepfake
    compressions:
    - c23
    contrast: false
    detection_level: video
    name: FFPP
    pack: true
    pair: false
    root_dir: ./datasets/ffpp/
    scale: 1.0
    types:
    - REAL
    - DF
    - FS
    - F2F
    - NT
  # - category: Deepfake
  #   name: DFDC
  #   pack: true
  #   root_dir: ./datasets/dfdc/
  #   scale: 0.1
  # - category: Deepfake
  #   name: CDF
  #   pack: true
  #   root_dir: ./datasets/cdf/
  #   scale: 1.0
  num_frames: 10
  train:
  - augmentation: normal+frame+rrc
    category: Deepfake
    compressions:
    - c23
    contrast: true
    detection_level: video
    name: FFPP
    pack: false
    pair: false
    root_dir: ./datasets/ffpp/
    scale: 1.0
    types:
    - REAL
    - DF
    - FS
    - F2F
    - NT
evaluator:
  batch_size: 24
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  # - name: deepfake/cdf
  #   types:
  #   - accuracy
  #   - roc_auc
  # - name: deepfake/dfdc
  #   types:
  #   - accuracy
  #   - roc_auc
  name: Evaluator
  num_workers: 8
model:
  optimizer: adamw
  frame_prompts: 10
  prompt_mode: deepc
  prompt_layers: 6
  num_classes: 4
  architecture: ViT-B/16
  decode_mode: 
    type: index
    indices: [6,7,8,9,10,11]
  op_mode:
    attn_mode: "frame+patch"
    attn_driver: ["smax"]
    frame_task: true
  train_mode:
    query_guide:
      type: normal
      key: k
      parts: ["lips", "skin","nose","eyes"]
      path: "./misc/real_semantic_patches_v3_1000.pickle"
  dropout: 0.5
  losses:
  - auc_roc
  name: Detector
  out_dim:
  - 2
  weight_decay: 0.01
system:
  deterministic_training: true
  evaluation_interval: 100
  evaluation_aggregate: 1
  mixed_precision: 'fp16'
  seed: 0
  training_eval_interval: 30
tracking:
  compare_fn: max
  directory: logs/vlvpt
  enabled: true
  main_metric: deepfake/ffpp/roc_auc
  project_name: VLVPT
  tool: wandb
trainer:
  early_stop: 20
  batch_accum: 3
  batch_size: 5
  learning_rate: 0.0005
  max_steps: 20000
  lr_scheduler: linear
  metrics:
  - name: deepfake/ffpp
    types:
    - accuracy
    - roc_auc
  mode:
    type: normal
  name: Trainer
  num_workers: 12
