tracking:
  enabled: true
  project_name: mix
  directory: logs/multi_evidence

model:
  out_dim: 
    - 180
    - 2
  losses:
    - kl_div
    - auc_roc

data:
  train:
    - name: rPPG
      dataset: RPPG
      train_ratio: 0.8
      compressions: 
        - "c23"
      label_type: dist
      label_dim: 180
      scale: 0.1
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "DF"
        - "FS"
        - "F2F"
      scale: 0.1
  eval:
    - name: rPPG
      dataset: RPPG
      train_ratio: 0.8
      compressions: 
        - "c23"
      label_type: dist
      label_dim: 180
      scale: 0.1
    - name: Deepfake
      dataset: FFPP
      compressions: 
        - "c23"
      types:
        - "REAL"
        - "NT"
      scale: 0.1

trainer:
  batch_size: 10
  learning_rate: 0.0003
  max_steps: 100
  teach_at: 10
  num_workers: 0
  metrics:
    - name: rPPG
      types:
        - mse
    - name: Deepfake
      types:
        - accuracy
        - roc_auc


evaluator:
  batch_size: 5
  num_workers: 8
  metrics:
    - name: rPPG
      types:
        - mse
    - name: Deepfake
      types:
        - accuracy
        - roc_auc

system:
  deterministic_training: true
  training_eval_interval: 5
  evaluation_interval: 10

