tracking:
  enabled: true
  project_name: FS
  directory: logs/cross-manipulation-raw

data:
  train:
    types:
    - REAL
    - DF
    - F2F
    - NT
  eval:
    - name: validation
      types:
      - REAL
      - FS

system:
  deterministic_training: true

